// api/generate.js
export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { chapter } = req.body;
  const apiKey = process.env.XAI_API_KEY;

  if (!apiKey) {
    return res.status(500).json({ error: 'API key not configured on backend' });
  }

  const topics = {
    physics: ["Electricity", "Light - Reflection and Refraction", "Magnetic Effects of Electric Current"],
    chemistry: ["Chemical Reactions and Equations", "Acids, Bases and Salts", "Metals and Non-metals"],
    biology: ["Life Processes", "How do Organisms Reproduce", "Heredity and Evolution"]
  };

  let category = chapter === "all" 
    ? ["physics", "chemistry", "biology"][Math.floor(Math.random() * 3)]
    : chapter;

  const topicList = topics[category] || topics.physics;
  const topic = topicList[Math.floor(Math.random() * topicList.length)];

  const prompt = `You are an expert CBSE Class 10 Science teacher preparing students for board exams.
Generate ONE fresh, original question on topic: ${topic} (${category.toUpperCase()}).
Question must be board-exam style (1 to 5 marks).
Return ONLY valid JSON with these exact keys, nothing else:
{
  "title": "${topic}",
  "text": "full question text here",
  "type": "mcq or numerical",
  "options": ["option1", "option2", "option3", "option4"] (only if mcq, else null),
  "answer": "exact correct answer",
  "explanation": "clear short explanation"
}
Make it different from previous questions.`;

  try {
    const response = await fetch("https://api.x.ai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`
      },
      body: JSON.stringify({
        model: "grok-4-0709",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.9,
        max_tokens: 700
      })
    });

    const data = await response.json();
    const content = data.choices[0].message.content.trim();

    // Extract JSON
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    const q = jsonMatch ? JSON.parse(jsonMatch[0]) : {
      title: topic,
      text: "Explain " + topic,
      type: "numerical",
      answer: "Concept based answer expected",
      explanation: "Generated by Grok"
    };

    res.status(200).json(q);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "AI generation failed" });
  }
}
